name: Android Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Change to the desired runner environment if needed

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          distribution: 'cmdline-tools'
          cmd-version: 'latest'

      - name: Build SampleApplication
        run: ./gradlew --no-daemon build
