name: Android Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Download Dependencies
        run: ./gradlew androidDependencies

      - name: Build project
        run: ./gradlew build

      - name: Run lint and tests
        run: ./gradlew lint test

      - name: Archive APKs
        uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: app/build/outputs/apk/debug/

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: app/build/reports
