name: Android Build

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Change to the desired runner environment if needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the desired Java version, make sure it's compatible with your project

      - name: Download Android Dependencies
        run: |
          yes | sdkmanager --update
          yes | sdkmanager "platforms;android-30"
          yes | sdkmanager "build-tools;30.0.3"
          yes | sdkmanager --licenses

      - name: Set up Gradle
        run: chmod +x ./gradlew

      - name: Restore Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Build and Test
        run: ./gradlew build lint test

      - name: Save Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Upload Build Reports
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: app/build/reports

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/
